# Generated by Django 3.1.2 on 2022-06-09 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name ')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name * ')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('phone_number', models.PositiveBigIntegerField(blank=True, help_text='Optional', null=True, verbose_name='Phone Number ')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='Address ')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile image', verbose_name='Profile Image')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'All Users',
                'verbose_name_plural': 'All Users',
            },
        ),
    ]
