# Generated by Django 3.1.2 on 2022-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, null=True)),
                ('contact_type', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.URLField(null=True)),
                ('tags', models.CharField(max_length=100, null=True)),
                ('address_street_1', models.CharField(max_length=100, null=True)),
                ('address_street_2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
