# Generated by Django 3.1.2 on 2022-06-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tittle',
            new_name='title',
        ),
    ]
