# Generated by Django 3.1.2 on 2022-06-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20220610_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_type',
        ),
    ]
