# Generated by Django 3.1.2 on 2022-06-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_company_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(max_length=100, null=True)),
                ('refrence', models.CharField(max_length=100, null=True)),
                ('industry', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='internal_notes',
            field=models.TextField(null=True),
        ),
    ]
