# Generated by Django 3.1.2 on 2022-06-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20220610_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('address_street_1', models.CharField(max_length=100, null=True)),
                ('address_street_2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('job_position', models.CharField(max_length=100, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.URLField(null=True)),
                ('sr_title', models.CharField(max_length=100, null=True)),
                ('tags', models.CharField(max_length=100, null=True)),
                ('internal_notes', models.TextField(null=True)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master.company')),
            ],
        ),
    ]
