# Generated by Django 3.1.2 on 2022-06-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='individual',
            name='individual_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
