# Generated by Django 3.1.8 on 2022-06-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20220613_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales_purchase',
        ),
        migrations.AddField(
            model_name='individual',
            name='industry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='refrence',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='sales_person',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
