# Generated by Django 3.1.8 on 2022-06-13 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20220613_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppertunity', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('expected_revenue', models.IntegerField(null=True)),
                ('star', models.CharField(max_length=5, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Qualified', 'Qualified'), ('Propostion', 'Propostion'), ('Won', 'Won')], max_length=100, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master.company')),
            ],
        ),
    ]
