# Generated by Django 3.1.8 on 2022-06-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_pipeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='star',
            new_name='rating',
        ),
    ]
